# Generated by Django 2.1.7 on 2019-03-19 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20190319_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'My Subscriber', 'verbose_name_plural': 'A lot of Subscribers'},
        ),
    ]
