# Generated by Django 2.1.7 on 2019-03-25 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_auto_20190321_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='sex',
        ),
    ]
