# Generated by Django 2.1.7 on 2019-03-25 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20190325_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinorder',
            options={'verbose_name': 'Товар в Заказе', 'verbose_name_plural': 'Товары в Заказе'},
        ),
    ]
